# Generated by Django 3.2.4 on 2021-06-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_complte_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
